version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: ember-auto-import
    versions:
    - 1.10.1
  - dependency-name: ember-concurrency
    versions:
    - 1.3.0
    - 2.0.1
    - 2.0.2
  - dependency-name: ember-simple-auth
    versions:
    - 3.0.1
    - 3.1.0
  - dependency-name: ember-cli
    versions:
    - 3.24.0
    - 3.25.0
